---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
data <- read.csv(unz("activity.zip", "activity.csv"), na.strings = "NA")
data$date <- as.Date(as.character(data$date), "%Y-%m-%d")
str(data)
```


## What is mean total number of steps taken per day?
```{r}
steps <- tapply(data$steps, data$date, sum, na.rm = T)
hist(steps, breaks=20, col="lightgreen", xlab="Steps", 
     main="Total Number of Steps Taken Per Day")
rug(jitter(steps, amount=100))
abline(v=mean(steps), col="blue", lwd=2)
abline(v=median(steps), col="green3", lwd=2, lty=2)
legend("topright", c("mean", "median"), col=c("blue", "green3"), 
       lty=c(1, 2), lwd=c(2, 2), bty="n")
mean(steps)
median(steps)
```


## What is the average daily activity pattern?
```{r}
pattern <- tapply(data$steps, data$interval, mean, na.rm = T)
plot(pattern, type = "l")
pattern[which.max(pattern)]
```


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
